# -*- coding: utf-8 -*-
"""Regressao miniNIR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19YtRSbnc3ZKIliICPlGF4tzNRwBM07PU

Leitura e organização do dataset (features LED1–LED6 e variáveis-alvo: ureia/
creatinina/albumina), garantindo consistência de tipos e ausência de valores inválidos.
Pré-processamento inserido no pipeline para evitar data leakage: aplicação de Savitzky–Golay (suavização/derivada com janela adaptada a 6 pontos) seguida de SNV (Standard Normal Variate) por amostra, e normalização/escala quando aplicável.
Prevenção de overfitting através de nested cross-validation (outer/inner loops): o loop interno otimiza hiperparâmetros e o loop externo fornece uma estimativa robusta da capacidade de generalização, reduzindo o risco de resultados otimistas.
Comparação de vários modelos de regressão (baselines regularizados e modelos não lineares), com seleção automática do melhor modelo por analito com base em métricas de desempenho.
Avaliação e visualização: reporte de métricas (ex.: R², RMSE e MAE), PCA (treino e teste) com % de variância explicada em PC1/PC2 e gráfico Predicted vs Actual para o conjunto de validação.
Outputs reprodutíveis: geração automática de um Excel com tabelas-resumo (num formato pronto para integrar no artigo), export do modelo final em joblib (para inferência futura) e criação dos plots em PNG, empacotados num zip para download no Colab.
"""

import os
import numpy as np
import pandas as pd
import joblib
import matplotlib.pyplot as plt
from google.colab import files
import io
import os, shutil
from google.colab import files

from scipy.signal import savgol_filter

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, KFold, GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.decomposition import PCA

from sklearn.cross_decomposition import PLSRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import Ridge

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


RANDOM_STATE = 42


# -------------------------
# Preprocess: SavGol + SNV per sample (row)
# -------------------------
class SavGolSNV(BaseEstimator, TransformerMixin):
    """
    Applies Savitzky–Golay across the 6-LED vector (per sample) + SNV per sample.
    With only 6 features, the window must be small and odd (typically 5).
    """
    def __init__(self, window=5, poly=2, deriv=0):
        self.window = window
        self.poly = poly
        self.deriv = deriv

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        X = np.asarray(X, dtype=float)
        n_feat = X.shape[1]

        w = int(self.window)
        if w % 2 == 0:
            w += 1
        if w > n_feat:
            w = n_feat if n_feat % 2 == 1 else max(3, n_feat - 1)
        if w < 3:
            Xf = X.copy()
        else:
            # IMPORTANT: smooth along feature axis (axis=1)
            Xf = savgol_filter(
                X,
                window_length=w,
                polyorder=min(self.poly, w - 1),
                deriv=self.deriv,
                axis=1
            )

        # SNV per sample
        mu = Xf.mean(axis=1, keepdims=True)
        sd = Xf.std(axis=1, keepdims=True) + 1e-12
        return (Xf - mu) / sd


# -------------------------
# Metrics helpers
# -------------------------
def rmse(y_true, y_pred):
    return float(np.sqrt(mean_squared_error(y_true, y_pred)))

def reg_metrics(y_true, y_pred):
    return {
        "R2": float(r2_score(y_true, y_pred)),
        "RMSE": rmse(y_true, y_pred),
        "MAE": float(mean_absolute_error(y_true, y_pred)),
    }


# -------------------------
# Plots
# -------------------------
def plot_pred_vs_actual(y_true, y_pred, out_png, title):
    fig, ax = plt.subplots(figsize=(6.5, 5.5))
    ax.scatter(y_true, y_pred, alpha=0.75, edgecolors="k")
    lo = min(np.min(y_true), np.min(y_pred))
    hi = max(np.max(y_true), np.max(y_pred))
    ax.plot([lo, hi], [lo, hi])
    ax.set_xlabel("Actual concentration")
    ax.set_ylabel("Predicted concentration")
    ax.set_title(title)
    ax.grid(True)
    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def plot_pca_train_test(X_train_proc, y_train, X_test_proc, y_test, out_train_png, out_test_png, title_prefix):
    pca = PCA(n_components=2, random_state=RANDOM_STATE)
    Ztr = pca.fit_transform(X_train_proc)
    Zte = pca.transform(X_test_proc)

    pc1 = pca.explained_variance_ratio_[0] * 100
    pc2 = pca.explained_variance_ratio_[1] * 100

    def _scatter(Z, y, out_png, suffix):
        fig, ax = plt.subplots(figsize=(7, 5.5))
        sc = ax.scatter(Z[:, 0], Z[:, 1], c=y, alpha=0.85)
        cb = fig.colorbar(sc, ax=ax)
        cb.set_label("Concentration")
        ax.set_title(f"{title_prefix} | {suffix}")
        ax.set_xlabel(f"PC1 ({pc1:.1f}%)")
        ax.set_ylabel(f"PC2 ({pc2:.1f}%)")
        ax.grid(True)
        fig.tight_layout()
        fig.savefig(out_png, dpi=200)
        plt.close(fig)

    _scatter(Ztr, y_train, out_train_png, "Train")
    _scatter(Zte, y_test, out_test_png, "Test")
    return float(pc1), float(pc2)


# -------------------------
# Model registry (same spirit as your v3 snippet, but regularised & tuned with nested CV)
# -------------------------
def model_grids():
    """
    Returns dict of model_name -> (estimator, param_grid, uses_scaler)
    All models run inside a pipeline with: SavGolSNV -> StandardScaler (optional) -> model
    """
    grids = {}

    # PLS (linear latent variables)
    grids["PLS"] = (
        PLSRegression(),
        {"model__n_components": [1, 2, 3, 4, 5]},
        True
    )

    # SVR (RBF)
    grids["SVR_RBF"] = (
        SVR(kernel="rbf"),
        {"model__C": [0.5, 1, 5, 10],
         "model__gamma": ["scale", 0.5, 0.1, 0.01],
         "model__epsilon": [0.01, 0.05, 0.1]},
        True
    )

    # Ridge (strong baseline, good against overfitting)
    grids["Ridge"] = (
        Ridge(random_state=RANDOM_STATE),
        {"model__alpha": [0.1, 1.0, 10.0, 50.0, 100.0]},
        True
    )

    # Tree ensembles (controlled depth/leaf to reduce overfitting)
    grids["RandomForest"] = (
        RandomForestRegressor(random_state=RANDOM_STATE),
        {"model__n_estimators": [400, 800],
         "model__max_depth": [None, 5, 8, 12],
         "model__min_samples_leaf": [2, 5, 10],
         "model__max_features": ["sqrt", 0.6, 1.0]},
        False
    )

    grids["GradientBoosting"] = (
        GradientBoostingRegressor(random_state=RANDOM_STATE),
        {"model__n_estimators": [300, 600],
         "model__learning_rate": [0.03, 0.05, 0.1],
         "model__max_depth": [2, 3, 4],
         "model__subsample": [0.7, 0.9, 1.0]},
        False
    )

    return grids


# -------------------------
# Nested CV selection (mitigates overfitting)
# -------------------------
def nested_cv_select_best(X, y, outer_splits=5, inner_splits=4, scoring="neg_root_mean_squared_error"):
    """
    Nested CV:
      outer loop -> unbiased generalization estimate per model
      inner loop -> hyperparameter tuning
    Returns:
      - df_nested: per-model outer mean/std (RMSE, R2)
      - best_model_name: chosen by lowest outer RMSE (mean)
    """
    outer = KFold(n_splits=outer_splits, shuffle=True, random_state=RANDOM_STATE)

    rows = []
    for name, (est, grid, uses_scaler) in model_grids().items():
        outer_rmse = []
        outer_r2 = []

        for tr_idx, te_idx in outer.split(X):
            X_tr, X_te = X[tr_idx], X[te_idx]
            y_tr, y_te = y[tr_idx], y[te_idx]

            steps = [("pre", SavGolSNV(window=5, poly=2, deriv=0))]
            if uses_scaler:
                steps.append(("scaler", StandardScaler()))
            steps.append(("model", est))
            pipe = Pipeline(steps)

            inner = KFold(n_splits=inner_splits, shuffle=True, random_state=RANDOM_STATE)
            gs = GridSearchCV(pipe, grid, scoring=scoring, cv=inner, n_jobs=-1)
            gs.fit(X_tr, y_tr)
            best = gs.best_estimator_

            yhat = best.predict(X_te)
            outer_rmse.append(rmse(y_te, yhat))
            outer_r2.append(r2_score(y_te, yhat))

        rows.append({
            "Model": name,
            "NestedCV_RMSE_mean": float(np.mean(outer_rmse)),
            "NestedCV_RMSE_std": float(np.std(outer_rmse)),
            "NestedCV_R2_mean": float(np.mean(outer_r2)),
            "NestedCV_R2_std": float(np.std(outer_r2)),
        })

    df_nested = pd.DataFrame(rows).sort_values("NestedCV_RMSE_mean", ascending=True).reset_index(drop=True)
    best_model_name = df_nested.loc[0, "Model"]
    return df_nested, best_model_name


# -------------------------
# Final fit on hold-out split (train/test) using the chosen model
# -------------------------
def fit_best_final(X_train, y_train, X_test, y_test, best_model_name, inner_splits=4,
                   scoring="neg_root_mean_squared_error"):
    est, grid, uses_scaler = model_grids()[best_model_name]

    steps = [("pre", SavGolSNV(window=5, poly=2, deriv=0))]
    if uses_scaler:
        steps.append(("scaler", StandardScaler()))
    steps.append(("model", est))
    pipe = Pipeline(steps)

    inner = KFold(n_splits=inner_splits, shuffle=True, random_state=RANDOM_STATE)
    gs = GridSearchCV(pipe, grid, scoring=scoring, cv=inner, n_jobs=-1)
    gs.fit(X_train, y_train)
    best_pipe = gs.best_estimator_
    best_params = gs.best_params_

    yhat_tr = best_pipe.predict(X_train)
    yhat_te = best_pipe.predict(X_test)

    m_tr = reg_metrics(y_train, yhat_tr)
    m_te = reg_metrics(y_test, yhat_te)

    return best_pipe, best_params, m_tr, m_te, yhat_te


# -------------------------
# Excel: template-like summary (similar to "MiniNIR output.xlsx")
# -------------------------
def build_template_like_sheet(wb, sheet_name, summary_rows, title="Inferência\n(sol compostas)"):
    """
    Creates a summary sheet with a layout similar to the provided MiniNIR output template:
      Row1: title at col G
      Row2: headers
      Next: blocks per analyte with rows for each algorithm (incl. best model + others)
    We include both NestedCV (training-like) and Holdout Test (validation-like) columns.
    """
    if sheet_name in wb.sheetnames:
        del wb[sheet_name]
    ws = wb.create_sheet(sheet_name)

    thin = Side(border_style="thin", color="999999")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    header_fill = PatternFill("solid", fgColor="D9E1F2")
    bold = Font(bold=True)

    # Title
    ws["G1"].value = title
    ws["G1"].font = Font(bold=True)

    # Headers (row 2)
    headers = [
        "Analito", "Algoritmo regressão",
        "NestedCV R2", "NestedCV RMSE", "NestedCV MAE",
        "Validação R2", "Validação RMSE", "Validação MAE",
        "Best params"
    ]
    for j, h in enumerate(headers, start=1):
        cell = ws.cell(2, j)
        cell.value = h
        cell.font = bold
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = border

    r = 3
    for row in summary_rows:
        vals = [
            row["Analyte"],
            row["Model"],
            row.get("NestedCV_R2", np.nan),
            row.get("NestedCV_RMSE", np.nan),
            row.get("NestedCV_MAE", np.nan),
            row.get("Test_R2", np.nan),
            row.get("Test_RMSE", np.nan),
            row.get("Test_MAE", np.nan),
            row.get("Best_params", "")
        ]
        for j, v in enumerate(vals, start=1):
            c = ws.cell(r, j)
            c.value = v
            c.border = border
            c.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        r += 1

    # Column widths
    widths = [14, 20, 12, 14, 12, 12, 14, 12, 45]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[get_column_letter(i)].width = w

    return ws

uploaded = files.upload()

def main():
    # ---- input paths (edit if needed) ----
    #CSV_PATH = "2025.02.12-miniNir (solucoes compostas)-Global.csv"
    OUT_XLSX = "miniNIR__REGRESSION__OUTPUT.xlsx"
    OUT_DIR = "miniNIR_regression_outputs"
    os.makedirs(OUT_DIR, exist_ok=True)

    # ---- load data ----
    df = pd.read_csv('2025.02.12-miniNir (solucoes compostas)-Global.csv', sep=";", decimal=",", encoding="latin-1")

    led_cols = [f"LED{i}_avg" for i in range(1, 7)]
    targets = {
        "Albumina": "Conc Albumina",
        "Creatinina": "Conc Creatinina",
        "Ureia": "Conc Ureia"
    }

    # predictors
    X = df[led_cols].to_numpy(dtype=float)

    # hold-out split (same split for all targets to keep comparability)
    idx = np.arange(len(df))
    tr_idx, te_idx = train_test_split(
        idx, test_size=0.2, random_state=RANDOM_STATE, shuffle=True
    )
    X_train, X_test = X[tr_idx], X[te_idx]

    # For PCA plots, we use the same preprocessing as in pipelines (but fitted on train only)
    vis_pre = Pipeline([
        ("pre", SavGolSNV(window=5, poly=2, deriv=0)),
        ("scaler", StandardScaler())
    ])
    Xtr_vis = vis_pre.fit_transform(X_train)
    Xte_vis = vis_pre.transform(X_test)

    # Storage
    all_metrics_sheets = {}
    summary_rows = []

    for analyte, ycol in targets.items():
        y = df[ycol].to_numpy(dtype=float)
        y_train, y_test = y[tr_idx], y[te_idx]

        # --- nested CV for model choice (anti-overfit) ---
        df_nested, best_model_name = nested_cv_select_best(
            X_train, y_train, outer_splits=5, inner_splits=4,
            scoring="neg_root_mean_squared_error"
        )

        # --- final fit on train and eval on test ---
        best_pipe, best_params, m_tr, m_te, yhat_test = fit_best_final(
            X_train, y_train, X_test, y_test,
            best_model_name, inner_splits=4,
            scoring="neg_root_mean_squared_error"
        )

        # Save joblib
        bundle = {
            "task": f"regression_{analyte.lower()}",
            "pipeline": best_pipe,
            "feature_cols": led_cols,
            "target_col": ycol,
            "best_model_name": best_model_name,
            "best_params": best_params
        }
        joblib_path = os.path.join(OUT_DIR, f"miniNIR_{analyte}__best_model.joblib")
        joblib.dump(bundle, joblib_path)

        # Plots: PCA train/test with % (color by concentration)
        pc1, pc2 = plot_pca_train_test(
            Xtr_vis, y_train, Xte_vis, y_test,
            out_train_png=os.path.join(OUT_DIR, f"PCA_{analyte}__train.png"),
            out_test_png=os.path.join(OUT_DIR, f"PCA_{analyte}__test.png"),
            title_prefix=f"miniNIR PCA | {analyte}"
        )

        # Predicted vs actual (validation/test)
        plot_pred_vs_actual(
            y_test, yhat_test,
            out_png=os.path.join(OUT_DIR, f"Pred_vs_Actual_{analyte}__test.png"),
            title=f"Predicted vs Actual (TEST) | {analyte} | Best={best_model_name}"
        )

        # Build per-analyte metrics table
        # We include nested CV summary + final metrics
        best_nested_row = df_nested[df_nested["Model"] == best_model_name].iloc[0].to_dict()
        metrics_row = {
            "Analyte": analyte,
            "BestModel": best_model_name,
            "NestedCV_RMSE_mean": best_nested_row["NestedCV_RMSE_mean"],
            "NestedCV_RMSE_std": best_nested_row["NestedCV_RMSE_std"],
            "NestedCV_R2_mean": best_nested_row["NestedCV_R2_mean"],
            "NestedCV_R2_std": best_nested_row["NestedCV_R2_std"],
            "Train_R2": m_tr["R2"],
            "Train_RMSE": m_tr["RMSE"],
            "Train_MAE": m_tr["MAE"],
            "Test_R2": m_te["R2"],
            "Test_RMSE": m_te["RMSE"],
            "Test_MAE": m_te["MAE"],
            "PC1_pct": pc1,
            "PC2_pct": pc2,
            "Best_params": str(best_params),
            "Joblib": os.path.basename(joblib_path)
        }
        all_metrics_sheets[analyte] = (df_nested, metrics_row)

        # summary rows for template-like sheet: include all models (nested) and fill test only for best
        for _, r in df_nested.iterrows():
            summary_rows.append({
                "Analyte": analyte,
                "Model": r["Model"],
                "NestedCV_R2": r["NestedCV_R2_mean"],
                "NestedCV_RMSE": r["NestedCV_RMSE_mean"],
                "NestedCV_MAE": np.nan,  # not computed in nested stage (optional)
                "Test_R2": m_te["R2"] if r["Model"] == best_model_name else np.nan,
                "Test_RMSE": m_te["RMSE"] if r["Model"] == best_model_name else np.nan,
                "Test_MAE": m_te["MAE"] if r["Model"] == best_model_name else np.nan,
                "Best_params": str(best_params) if r["Model"] == best_model_name else ""
            })

    # Write Excel
    with pd.ExcelWriter(os.path.join(OUT_DIR, OUT_XLSX), engine="openpyxl") as xw:
        # Per analyte: nested model comparison + one-row final metrics
        for analyte, (df_nested, metrics_row) in all_metrics_sheets.items():
            df_nested.to_excel(xw, index=False, sheet_name=f"{analyte}_NestedCV")
            pd.DataFrame([metrics_row]).to_excel(xw, index=False, sheet_name=f"{analyte}_Final")

    # Add template-like sheet using openpyxl
    xlsx_path = os.path.join(OUT_DIR, OUT_XLSX)
    wb = openpyxl.load_workbook(xlsx_path)
    build_template_like_sheet(wb, "Tabela_formato_template", summary_rows)
    wb.save(xlsx_path)

    print("OK ✅")
    print("Outputs in:", OUT_DIR)
    print("Excel:", xlsx_path)


if __name__ == "__main__":
    main()

    # --- PACK OUTPUTS FOR DOWNLOAD (Colab) ---

out_dir = "miniNIR_regression_outputs"  # ajustar se for outro
zip_base = out_dir
zip_file = f"{zip_base}.zip"

if os.path.isdir(out_dir):
    if os.path.exists(zip_file):
        os.remove(zip_file)
    shutil.make_archive(zip_base, "zip", out_dir)
    print("Created:", zip_file)
    files.download(zip_file)
else:
    print("Output dir not found:", out_dir)
    print("Current dir:", os.getcwd())