# -*- coding: utf-8 -*-
"""Classification (FTIR-NIR)_Estadio_Sem preprocessamento_Inference_v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xRcOqX9ZzmDKFROXJT_L2iJI6hI0nPDC
"""

from IPython import get_ipython
from IPython.display import display
# %%
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPRegressor
from sklearn.cross_decomposition import PLSRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (r2_score, confusion_matrix, mean_squared_error, ConfusionMatrixDisplay, roc_auc_score, roc_curve, accuracy_score,
                             precision_score, recall_score, f1_score, auc)
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold
import seaborn as sns
import pickle
import seaborn as sns
import xgboost as xgb
from xgboost import XGBClassifier #Import XGBClassifier
from scipy.stats import bootstrap
import matplotlib.pyplot as plt
from google.colab import files
import io

# Load the dataset
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['Simples - Espetros Creatinina (Estadio) (1).csv']), delimiter=';', encoding='latin-1')
print(data)

# Replace commas with periods in numeric columns
for column in data.columns:
  # Check if the column data type is 'object' (likely string) before applying str methods
   if data[column].dtype == 'object':
    # Try converting the column to numeric, errors='coerce' will replace invalid values with NaN
    data[column] = pd.to_numeric(data[column].str.replace(',', '.', regex=True), errors='coerce')
    # Now fill NaN values with 0. This is a simple choice, consider other imputation strategies if necessary
    data[column] = data[column].fillna(0)

# Extract the wavelengths (columns E to FMQ) and the target variable 'Estadio'
features = data.iloc[:, 4:-1]  # Wavelengths (columns E to FMQ)
target = data['Estadio']       # Target variable 'Estadio'

# Function to calculate specificity
def specificity_score(y_true, y_pred):
      # Get unique classes
    classes = np.unique(y_true)

    # Handle binary case directly
    if len(classes) == 2:
        tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
        return tn / (tn + fp) if (tn + fp) > 0 else 0  # Avoid division by zero

    # Handle multiclass using one-vs-rest
    specificity_values = []
    for cls in classes:
        # Create a binary view of the multiclass data for one class vs all others
        y_true_binary = (y_true == cls).astype(int)
        y_pred_binary = (y_pred == cls).astype(int)
        tn, fp, fn, tp = confusion_matrix(y_true_binary, y_pred_binary).ravel()
        specificity = tn / (tn + fp) if (tn + fp) > 0 else 0  # Avoid division by zero
        specificity_values.append(specificity)

    # Return the mean specificity
    return np.mean(specificity_values)


# Function to select a specific wavelength range
def select_wavelength_range(features, start_col, end_col):
    return features.iloc[:, start_col:end_col]

# Function to train and evaluate the model
def train_and_evaluate(clf, X_train, X_test, y_train, y_test):
    clf.fit(X_train, y_train)

    # Predictions
    y_train_pred = clf.predict(X_train)
    y_test_pred = clf.predict(X_test)

    # Evaluation metrics for training set
    train_accuracy = accuracy_score(y_train, y_train_pred)
    train_precision = precision_score(y_train, y_train_pred, average='weighted')
    train_recall = recall_score(y_train, y_train_pred, average='weighted')
    train_f1 = f1_score(y_train, y_train_pred, average='weighted')
    train_specificity = specificity_score(y_train, y_train_pred)

    # Evaluation metrics for validation set
    test_accuracy = accuracy_score(y_test, y_test_pred)
    test_precision = precision_score(y_test, y_test_pred, average='weighted')
    test_recall = recall_score(y_test, y_test_pred, average='weighted')
    test_f1 = f1_score(y_test, y_test_pred, average='weighted')
    test_specificity = specificity_score(y_test, y_test_pred)

    return {
        'train_accuracy': train_accuracy,
        'train_precision': train_precision,
        'train_recall': train_recall,
        'train_f1': train_f1,
        'train_specificity': train_specificity,
        'test_accuracy': test_accuracy,
        'test_precision': test_precision,
        'test_recall': test_recall,
        'test_f1': test_f1,
        'test_specificity': test_specificity
    }

# Example: Select a specific wavelength range (e.g., columns 10 to 50)
start_col = 3300
end_col = 3449
features_selected = select_wavelength_range(features, start_col, end_col)

# We also need to subset the target variable to match the selected features
target_selected = target.iloc[features_selected.index]

# Perform PCA visualization on the selected wavelength range
scaler = StandardScaler()
features_selected_scaled = scaler.fit_transform(features_selected)  # Scale the selected features
pca = PCA(n_components=2)
pca_components_selected = pca.fit_transform(features_selected_scaled)  # Apply PCA to the selected features
explained_variance_selected = pca.explained_variance_ratio_ * 100

# Plot the PCA visualization for the selected wavelength range
plt.figure(figsize=(10, 6))
scatter = plt.scatter(pca_components_selected[:, 0], pca_components_selected[:, 1], c=target_selected, cmap='coolwarm', alpha=0.7)
plt.xlabel(f'Principal Component 1 ({explained_variance_selected[0]:.2f}%)')
plt.ylabel(f'Principal Component 2 ({explained_variance_selected[1]:.2f}%)')
plt.title(f'PCA Visualization of the Selected Wavelength Range ({start_col} to {end_col})')
cbar = plt.colorbar(scatter)
cbar.set_label('Predicted Variable')
plt.show()

# Define classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42),
    "XGBoost": XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42),
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42)
}

# Cross-validation and model evaluation
cv_folds = 5
auc_scores = {}
models = {}
metrics_results = {}


# Scale the selected features
features_selected_scaled = scaler.fit_transform(features_selected)

# Split the selected wavelength data into training and validation sets
X_train_selected, X_test_selected, y_train_selected, y_test_selected = train_test_split(features_selected_scaled, target, test_size=0.3, random_state=42)

# Now, use X_train_selected and X_test_selected for training and evaluation
for name, clf in classifiers.items():
    # Evaluate on the selected wavelength range
    selected_wavelength_metrics = train_and_evaluate(clf, X_train_selected, X_test_selected, y_train_selected, y_test_selected)

    # Store metrics
    metrics_results[name] = {
        'selected_wavelength': selected_wavelength_metrics
    }

    # ROC AUC for the selected wavelength range
    y_proba_selected = clf.predict_proba(X_test_selected)
    roc_auc_selected = roc_auc_score(y_test_selected, y_proba_selected, multi_class='ovr')
    auc_scores[name] = roc_auc_selected
    models[name] = clf

    # Bootstrapping for confidence interval
    bootstrapped_scores = []
    # Reset index for y_test_selected
    y_test_selected_reset = y_test_selected.reset_index(drop=True)
    for _ in range(1000):
        indices = np.random.randint(0, len(y_test_selected_reset), len(y_test_selected_reset))
        unique_classes_resampled = np.unique(y_test_selected_reset[indices])
        if len(unique_classes_resampled) < len(np.unique(y_test_selected_reset)):
            continue

        resampled_y_proba = clf.predict_proba(X_test_selected[indices])
        score = roc_auc_score(y_test_selected_reset[indices], resampled_y_proba, multi_class='ovr')
        bootstrapped_scores.append(score)
    ci_lower, ci_upper = np.percentile(bootstrapped_scores, [2.5, 97.5])
    print(f"{name} - ROC AUC: {roc_auc_selected:.4f} (95% CI: {ci_lower:.4f} - {ci_upper:.4f})")

# Model comparison plot
plt.figure(figsize=(10, 6))
plt.bar(auc_scores.keys(), auc_scores.values(), color=['blue', 'orange', 'green'])
plt.ylabel("ROC AUC Score")
plt.title("Model Comparison")
plt.grid(axis='y')
plt.show()

# Print metrics for all models
for model_name, metrics in metrics_results.items():
    print(f"{model_name} Metrics:")
    print("  Selected Wavelength Range:")
    for metric, value in metrics['selected_wavelength'].items():
        print(f"    {metric}: {value:.4f}")
    print()

# Create a DataFrame for metrics summary
table_df = pd.DataFrame(metrics_results).T
print("\nSummary of Model Performance:")
print(table_df)

# Select the best model
best_model_name = max(auc_scores, key=auc_scores.get)
best_model = models[best_model_name]

# Predict and evaluate best model
y_pred = best_model.predict(X_test_selected)
y_proba = best_model.predict_proba(X_test_selected)
accuracy = accuracy_score(y_test_selected, y_pred)
precision = precision_score(y_test_selected, y_pred, average='weighted')
recall = recall_score(y_test_selected, y_pred, average='weighted')
f1 = f1_score(y_test_selected, y_pred, average='weighted')
roc_auc = roc_auc_score(y_test_selected, y_proba, multi_class='ovr')

print(f"Best Model: {best_model_name}")
print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")
print(f"ROC AUC: {roc_auc:.4f}")

# Save the best model
with open('best_model.pkl', 'wb') as file:
    pickle.dump((best_model, scaler), file)

# Confusion Matrix
conf_matrix = confusion_matrix(y_test_selected, y_pred)
ConfusionMatrixDisplay(conf_matrix).plot()
plt.title("Confusion Matrix")
plt.show()

# ROC Curve
# Get probabilities for the positive class for each class in a one-vs-rest approach
y_probs = best_model.predict_proba(X_test_selected)
n_classes = y_probs.shape[1]  # Get the number of classes

# Calculate and plot ROC curve for each class
plt.figure(figsize=(10, 6))
for i in range(n_classes):
    fpr, tpr, _ = roc_curve(y_test_selected, y_probs[:, i], pos_label=i)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], color='red', linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend()
plt.grid(True)
plt.show()

# Save the best model using the captured best_pls and best_scaler
with open('best_rf_model.pkl', 'wb') as file:
    pickle.dump((clf, scaler), file)

loaded_model = pickle.load(open('best_rf_model.pkl','rb'))

uploaded = files.upload()

# Load new dataset for inference
inference_data = pd.read_csv('_Inferencias compostas (creatinina) (1).csv', delimiter=';', encoding='latin-1')

# Replace commas with periods in numeric columns
for column in inference_data.columns:
    if inference_data[column].dtype == 'object':
        inference_data[column] = pd.to_numeric(inference_data[column].str.replace(',', '.'), errors='coerce').fillna(0)

# Extract features
inference_features = inference_data.reindex(columns=features.columns, fill_value=0)

inference_scaled = scaler.transform(inference_features)

# Predict
predicted_classes = clf.predict(inference_scaled)
predicted_proba = clf.predict_proba(inference_scaled)[:, 1]

# Append predictions
inference_data['Predicted_Class'] = predicted_classes
inference_data['Predicted_Proba'] = predicted_proba

# Save the resulting dataset
inference_data.to_csv('inference_results_classification.csv', index=False, sep=';')
print("Inference completed. Results saved to 'inference_results_classification.csv'.")

# Plot prediction probabilities
plt.figure(figsize=(10, 6))
sns.histplot(predicted_proba, bins=30, kde=True, color='blue', label='Predicted Probabilities')
plt.title('Distribution of Predicted Probabilities')
plt.xlabel('Probability')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True)
plt.show()

files.download('inference_results_classification.csv')