# -*- coding: utf-8 -*-
"""Iterative ANN (FTIR-NIR)_com_regularizacao_Inference_v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GVHuAgQaEW16J_ol3NxPLHUXQbhd1YjU
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.cross_decomposition import PLSRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, confusion_matrix, mean_squared_error, ConfusionMatrixDisplay
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import KFold
from sklearn.neural_network import MLPRegressor
import pickle
import matplotlib.pyplot as plt
from google.colab import files
import io

# Load the dataset
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['Compostas (Novas-creatinina) - Espetros.csv']), delimiter=';', encoding='latin-1')
print(data)

# Replace commas with periods in numeric columns
for column in data.columns:
  # Check if the column data type is 'object' (likely string) before applying str methods
   if data[column].dtype == 'object':
    # Try converting the column to numeric, errors='coerce' will replace invalid values with NaN
    data[column] = pd.to_numeric(data[column].str.replace(',', '.'), errors='coerce')
    # Now fill NaN values with 0. This is a simple choice, consider other imputation strategies if necessary
    data[column] = data[column].fillna(0)

# Extract the target and feature columns
target = data['Conc']
features = data.iloc[:, 4:]  # Assuming wavelength data starts at column E

# Function to evaluate a band with ANN and Ridge regularization
def evaluate_band_ann_ridge(start_col, end_col, hidden_layer_sizes=(100,), max_iter=1000, alpha=0.01):
    # Select features within the current band
    band_features = features.iloc[:, start_col:start_col + end_col]
    X_train, X_test, y_train, y_test = train_test_split(band_features, target, test_size=0.3, random_state=42)

    # Normalize the features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Perform PCA on the selected band of features
    pca = PCA(n_components=2)  # Use 2 components for visualization
    pca_components = pca.fit_transform(X_train_scaled)  # Apply PCA to the scaled training data

    # Calculate explained variance percentages
    explained_variance = pca.explained_variance_ratio_ * 100

    # Create a DataFrame for visualization
    pca_df = pd.DataFrame(pca_components, columns=['PCA1', 'PCA2'])
    pca_df['Conc'] = y_train.reset_index(drop=True)  # Use the training target values

    # Visualization of PCA results for the selected wavelength band
    plt.figure(figsize=(12, 6))
    for label in pca_df['Conc'].unique():
        subset = pca_df[pca_df['Conc'] == label]
        plt.scatter(subset['PCA1'], subset['PCA2'], label=label, alpha=0.7)

    plt.title(f'PCA Visualization of Conc (Selected Wavelength Band: {start_col}-{start_col + end_col})')
    plt.xlabel(f'Principal Component 1 ({explained_variance[0]:.2f}%)')
    plt.ylabel(f'Principal Component 2 ({explained_variance[1]:.2f}%)')
    plt.legend(title='Conc')
    plt.grid(True)
    plt.show()

    # Fit the ANN model with L2 regularization (alpha is the regularization strength)
    ann = MLPRegressor(hidden_layer_sizes=hidden_layer_sizes, max_iter=max_iter, alpha=alpha, random_state=42)
    ann.fit(X_train_scaled, y_train)

    # Predict on training and validation sets
    y_train_pred = ann.predict(X_train_scaled).flatten()
    y_test_pred = ann.predict(X_test_scaled).flatten()

    # Calculate R2 and RMSE for both training and validation sets
    r2_train = r2_score(y_train, y_train_pred)
    rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
    r2_test = r2_score(y_test, y_test_pred)
    rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

    print(f"ANN Regression on Selected Wavelengths: R2 (Train) = {r2_train:.4f}, RMSE (Train) = {rmse_train:.4f}")
    print(f"ANN Regression on Selected Wavelengths: R2 (Test) = {r2_test:.4f}, RMSE (Test) = {rmse_test:.4f}, Hidden Layers = {hidden_layer_sizes}")

    # Plot actual vs predicted concentrations for both training and validation sets
    plt.figure(figsize=(10, 6))
    plt.scatter(y_train, y_train_pred, alpha=0.7, label='Training Set')
    plt.scatter(y_test, y_test_pred, alpha=0.7, label='Validation Set')
    plt.plot([y_train.min(), y_train.max()], [y_train.min(), y_train.max()], 'r--', label='Ideal Fit')
    plt.xlabel('Actual Concentrations')
    plt.ylabel('Predicted Concentrations')
    plt.title('ANN Regression: Actual vs Predicted Concentrations (Selected Wavelengths)')
    plt.legend()
    plt.grid(True)
    plt.show()

    return pca_df, explained_variance, ann, scaler, r2_train, rmse_train, r2_test, rmse_test

# Example usage: Manually select wavelengths from column 10 to 60
start_col = 1
end_col = 4407
pca_df, explained_variance, ann_model, scaler, r2_train, rmse_train, r2_test, rmse_test = evaluate_band_ann_ridge(start_col, end_col, alpha=0.01)

# Print the ANN model performance
print(f"R2 Score (Train): {r2_train:.4f}")
print(f"RMSE (Train): {rmse_train:.4f}")
print(f"R2 Score (Test): {r2_test:.4f}")
print(f"RMSE (Test): {rmse_test:.4f}")

# Function to evaluate a band with ANN
def evaluate_band_ann(start_col, band_width, hidden_layer_sizes=(100,), max_iter=1000, n_splits=5):
    band_features = features.iloc[:, start_col:start_col + band_width]

    # Select features within the current band
    band_features = features.iloc[:, start_col:start_col + band_width]
    X_train, X_test, y_train, y_test = train_test_split(band_features, target, test_size=0.3, random_state=42)

    # Normalize the features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Apply PCA to the scaled training data
    pca = PCA(n_components=3)  # Adjust n_components as needed
    X_train_pca = pca.fit_transform(X_train_scaled)
    X_test_pca = pca.transform(X_test_scaled)  # Transform the test data using the same PCA object

    # Fit the ANN model
    ann = MLPRegressor(hidden_layer_sizes=hidden_layer_sizes, max_iter=max_iter, random_state=42)
    ann.fit(X_train_pca, y_train)

    # Predict on training and validation sets
    y_train_pred = ann.predict(X_train_pca).flatten()
    y_test_pred = ann.predict(X_test_pca).flatten()

    # Calculate R2 and RMSE for both training and validation sets
    r2_train = r2_score(y_train, y_train_pred)
    rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
    r2_test = r2_score(y_test, y_test_pred)
    rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

    return r2_train, rmse_train, r2_test, rmse_test, y_train, y_train_pred, y_test, y_test_pred, X_train_scaled, scaler, ann, pca

# Iteratively evaluate bands
band_widths = [50, 100, 150]  # Define possible band widths
best_r2 = -np.inf
best_band = None
results = []
best_y_test = None  # Initialize best_y_test
best_y_pred = None  # Initialize best_y_pred
best_pca_model = None  # Initialize best_pca_model
best_pca_explained_variance_ratio_ = None  # Initialize best_pca_explained_variance_ratio_
best_scaler = None  # Initialize best_scaler outside the loop
best_X_train = None  # Initialize best_X_train to store the training data for the best band
best_y_train = None  # Initialize best_y_train to store the training target for the best band
best_ann_model = None  # Initialize best_ann_model outside the loop to store the best model

for band_width in band_widths:
    for start_col in range(0, features.shape[1] - band_width + 1, band_width):  # Slide over features
        r2_train, rmse_train, r2_test, rmse_test, y_train, y_train_pred, y_test, y_test_pred, X_train_scaled, scaler, ann, pca = evaluate_band_ann(start_col, band_width)
        results.append({'start_col': start_col, 'band_width': band_width, 'R2_train': r2_train, 'RMSE_train': rmse_train, 'R2_test': r2_test, 'RMSE_test': rmse_test})
        if r2_test > best_r2:
            best_r2 = r2_test
            best_band = (start_col, band_width)
            best_y_test = y_test  # Store y_test for the best band
            best_y_pred = y_test_pred  # Store y_pred for the best band
            best_scaler = scaler  # Store the scaler for the best band
            best_X_train = X_train_scaled  # Store X_train for the best band
            best_y_train = y_train  # Store y_train for the best band
            best_ann_model = ann  # Assign the current 'ann' to 'best_ann_model'
            best_pca_model = pca  # Store the PCA model for the best band
            best_pca_explained_variance_ratio_ = pca.explained_variance_ratio_ * 100  # Store explained variance ratio

# Convert results to a DataFrame for analysis
results_df = pd.DataFrame(results)

# Display the best band
print(f"Best Band: Start Column = {best_band[0]}, Width = {best_band[1]}, R2 (Test) = {best_r2}, RMSE (Test) = {results_df.loc[results_df['R2_test'].idxmax(), 'RMSE_test']}")

# Visualization of R2 across bands
plt.figure(figsize=(10, 6))
for band_width in band_widths:
    subset = results_df[results_df['band_width'] == band_width]
    start_wavenumbers = [features.columns[i] for i in subset['start_col']]
    plt.plot(start_wavenumbers, subset['R2_test'], label=f'Width {band_width}')

plt.xlabel('Start Wavenumber')
plt.ylabel('R2 (Test)')
plt.legend()
plt.title('R2 Across Bands (ANN)')
plt.grid(True)
plt.show()

# Visualization for the best model
if best_pca_model is not None:
    # PCA Visualization for the best band
    pca_df = pd.DataFrame(best_pca_model.transform(best_scaler.transform(best_X_train))[:, :2], columns=['PCA1', 'PCA2'])
    pca_df['Conc'] = best_y_train.reset_index(drop=True)

    plt.figure(figsize=(12, 6))
    for label in pca_df['Conc'].unique():
        subset = pca_df[pca_df['Conc'] == label]
        plt.scatter(subset['PCA1'], subset['PCA2'], label=label, alpha=0.7)

    plt.title(f'PCA Visualization of Conc (Best Band: {best_band[0]}-{best_band[0] + best_band[1]})')
    plt.xlabel(f'Principal Component 1 ({best_pca_explained_variance_ratio_[0]:.2f}%)')
    plt.ylabel(f'Principal Component 2 ({best_pca_explained_variance_ratio_[1]:.2f}%)')
    plt.legend(title='Conc')
    plt.grid(True)
    plt.show()

    # Plot actual vs predicted concentrations for the best model
    plt.figure(figsize=(10, 6))
    plt.scatter(best_y_train, best_ann_model.predict(best_pca_model.transform(best_scaler.transform(best_X_train))), alpha=0.7, label='Training Set')
    plt.scatter(best_y_test, best_y_pred, alpha=0.7, label='Validation Set')
    plt.plot([best_y_train.min(), best_y_train.max()], [best_y_train.min(), best_y_train.max()], 'r--', label='Ideal Fit')
    plt.xlabel('Actual Concentrations')
    plt.ylabel('Predicted Concentrations')
    plt.title('ANN Regression: Actual vs Predicted Concentrations (Best Model)')
    plt.legend()
    plt.grid(True)
    plt.show()

# Visualize PCA components- Processed data
plt.figure(figsize=(10, 6))
plt.scatter(best_pca_model.components_[0], best_pca_model.components_[1], alpha=0.7)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA Score Plot (Processed Data)')
plt.show()

# Adjust confusion matrix for multi-class (use bins for classification)
num_bins = 5  # Example: categorize concentrations into 5 bins
# Get unique values for bins
unique_values = np.unique(np.concatenate((best_y_test, best_y_pred)))

# If unique values are less than num_bins, adjust num_bins
num_bins = min(num_bins, len(unique_values))

# Ensure at least 2 bins for the confusion matrix
num_bins = max(num_bins, 5)
y_test_bins = pd.cut(best_y_test, bins=num_bins, labels=False)
y_pred_bins = pd.cut(best_y_pred, bins=num_bins, labels=False)
conf_matrix = confusion_matrix(y_test_bins, y_pred_bins)
display_labels = np.arange(num_bins)
ConfusionMatrixDisplay(conf_matrix, display_labels=display_labels).plot()
plt.title(f"Confusion Matrix")
plt.show()

# Save the best model using the captured best_pls and best_scaler
with open('best_ann_model.pkl', 'wb') as file:
    pickle.dump((best_ann_model, best_scaler, best_band), file)

loaded_model = pickle.load(open('best_ann_model.pkl','rb'))

uploaded = files.upload()

# Load new dataset for inference
inference_data = pd.read_csv('Sol compostas (ureia)_inferencia.csv', delimiter=';', encoding='latin-1')

# Replace commas with periods in numeric columns
for column in inference_data.columns:
    if inference_data[column].dtype == 'object':
        inference_data[column] = pd.to_numeric(inference_data[column].str.replace(',', '.'), errors='coerce').fillna(0)

# Extract features and reduce to the best band
inference_features = inference_data.iloc[:, 4:]
band_start, band_width = best_band

# Align inference features with training features
training_columns = features.columns[band_start:band_start + band_width]
inference_band = inference_features.reindex(columns=training_columns, fill_value=0)

# Ensure band_start and band_width are within the bounds of inference_features
#band_start = min(band_start, inference_features.shape[1] - 1)
#band_width = min(band_width, inference_features.shape[1] - band_start)

#inference_band = inference_features.iloc[:, band_start:band_start + band_width]

# Convert inference_band columns to numeric if necessary
#for column in inference_band.columns:
    #if inference_band[column].dtype == 'object':  # Check if the column data type is 'object'
        #inference_band[column] = pd.to_numeric(inference_band[column].str.replace(',', '.'), errors='coerce').fillna(0)

# Get the column names used during training for the best band
#training_band_columns = features.columns[best_band[0]:best_band[0] + best_band[1]]

# Ensure inference_band has the same column names as training data
#inference_band = inference_band.reindex(columns=training_band_columns, fill_value=0)

# Preprocess inference data
inference_scaled = best_scaler.transform(inference_band)

# Apply PCA transformation using the loaded PCA model
inference_pca = best_pca_model.transform(inference_scaled) # This line is added

# Perform prediction
predicted_conc = loaded_model[0].predict(inference_pca).flatten()

# Append predictions to the dataset
inference_data = pd.concat([inference_data, pd.DataFrame({'Predicted_Conc': predicted_conc})], axis=1)

# Save the resulting dataset
inference_data.to_csv('inference_results.csv', index=False, sep=';')
print("Inference completed. Results saved to 'inference_results.csv'.")

# Plot inference data distribution
plt.figure(figsize=(10, 6))
plt.hist(predicted_conc, bins=30, alpha=0.7, label='Predicted Concentrations')
plt.title('Distribution of Predicted Concentrations (Inference)')
plt.xlabel('Concentration')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True)
plt.show()

files.download('inference_results.csv')