# -*- coding: utf-8 -*-
"""iterative Random Forest (FTIR-NIR)_com_regularizacao_com inferencia_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JsDPiTsGNERsWoqDpBPH-QVDaJMtsWUp
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.cross_decomposition import PLSRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import r2_score, confusion_matrix, mean_squared_error, ConfusionMatrixDisplay
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import Ridge
import pickle
import matplotlib.pyplot as plt
from google.colab import files
import io

# Load the dataset
uploaded = files.upload()

data = pd.read_csv(io.BytesIO(uploaded['Simples - Espetros Albumina (1).csv']), delimiter=';', encoding='latin-1')
print(data)

# Replace commas with periods in numeric columns
for column in data.columns:
  # Check if the column data type is 'object' (likely string) before applying str methods
   if data[column].dtype == 'object':
    # Try converting the column to numeric, errors='coerce' will replace invalid values with NaN
    data[column] = pd.to_numeric(data[column].str.replace(',', '.'), errors='coerce')
    # Now fill NaN values with 0. This is a simple choice, consider other imputation strategies if necessary
    data[column] = data[column].fillna(0)

# Extract the target and feature columns
target = data['Conc']
features = data.iloc[:, 4:]  # Assuming wavelength data starts at column E

# Modified function for Random Forest
def evaluate_band_rf(start_col, end_col, n_estimators=100, max_depth=None):
    # Select features within the current band
    band_features = features.iloc[:, start_col:start_col + end_col]
    X_train, X_test, y_train, y_test = train_test_split(band_features, target, test_size=0.3, random_state=42)

    # Normalize the features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Perform PCA (for visualization only)
    features_scaled = scaler.fit_transform(band_features)
    pca = PCA(n_components=2)
    pca_components = pca.fit_transform(features_scaled)
    explained_variance = pca.explained_variance_ratio_ * 100

    # Visualization (same as before)
    pca_df = pd.DataFrame(pca_components, columns=['PCA1', 'PCA2'])
    pca_df['Conc'] = target.values

    plt.figure(figsize=(12, 6))
    for label in pca_df['Conc'].unique():
        subset = pca_df[pca_df['Conc'] == label]
        plt.scatter(subset['PCA1'], subset['PCA2'], label=label, alpha=0.7)
    plt.title(f'PCA Visualization of Conc (Selected Wavelength Band: {start_col}-{start_col + end_col})')
    plt.xlabel(f'Principal Component 1 ({explained_variance[0]:.2f}%)')
    plt.ylabel(f'Principal Component 2 ({explained_variance[1]:.2f}%)')
    plt.legend(title='Conc')
    plt.grid(True)
    plt.show()

    # Train Random Forest model
    rf = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, random_state=42)
    rf.fit(X_train_scaled, y_train)

    # Predictions
    y_train_pred = rf.predict(X_train_scaled)
    y_test_pred = rf.predict(X_test_scaled)

    # Calculate metrics
    r2_train = r2_score(y_train, y_train_pred)
    rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
    r2_test = r2_score(y_test, y_test_pred)
    rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

    print(f"Random Forest on Selected Wavelengths: R2 (Train) = {r2_train:.4f}, RMSE (Train) = {rmse_train:.4f}")
    print(f"Random Forest on Selected Wavelengths: R2 (Test) = {r2_test:.4f}, RMSE (Test) = {rmse_test:.4f}")

    # Plot actual vs predicted
    plt.figure(figsize=(10, 6))
    plt.scatter(y_train, y_train_pred, alpha=0.7, label='Training Set')
    plt.scatter(y_test, y_test_pred, alpha=0.7, label='Validation Set')
    plt.plot([y_train.min(), y_train.max()], [y_train.min(), y_train.max()], 'r--', label='Ideal Fit')
    plt.xlabel('Actual Concentrations')
    plt.ylabel('Predicted Concentrations')
    plt.title('Random Forest: Actual vs Predicted Concentrations')
    plt.legend()
    plt.grid(True)
    plt.show()

    return pca_df, explained_variance, rf, scaler, r2_train, rmse_train, r2_test, rmse_test

# Example usage
start_col = 4100
end_col = 50
pca_df, explained_variance, rf, scaler, r2_train, rmse_train, r2_test, rmse_test = evaluate_band_rf(start_col, end_col)

# Random Forest on the whole spectrum
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

rf_full = RandomForestRegressor(n_estimators=100, random_state=42)
rf_full.fit(X_train_scaled, y_train)

y_pred = rf_full.predict(X_test_scaled)
r2 = r2_score(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f"Random Forest on Full Spectrum: R2 = {r2:.4f}, RMSE = {rmse:.4f}")

# Plot full spectrum results
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', label='Ideal Fit')
plt.xlabel('Actual Concentrations')
plt.ylabel('Predicted Concentrations')
plt.title('Random Forest:   (Full Spectrum)')
plt.legend()
plt.grid(True)
plt.show()

def evaluate_band_rf_iter(start_col, band_width, n_estimators=100, max_depth=15):
    band_features = features.iloc[:, start_col:start_col + band_width]
    X_train, X_test, y_train, y_test = train_test_split(band_features, target, test_size=0.3, random_state=42)

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    rf = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth, random_state=42)
    rf.fit(X_train_scaled, y_train)

    y_train_pred = rf.predict(X_train_scaled)
    y_test_pred = rf.predict(X_test_scaled)

    r2_train = r2_score(y_train, y_train_pred)
    rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))
    r2_test = r2_score(y_test, y_test_pred)
    rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

    return r2_train, rmse_train, r2_test, rmse_test, y_train, y_train_pred, y_test, y_test_pred, X_train_scaled, scaler, rf, X_train, y_train

# Iteratively evaluate bands with metrics tracking
band_widths = [50, 100, 150]
best_r2 = -np.inf
best_band = None
results = []
best_y_test = None
best_y_pred = None
best_y_train = None
best_y_train_pred = None
best_scaler = None
best_X_train = None
best_model = None

for band_width in band_widths:
    for start_col in range(0, features.shape[1] - band_width + 1, band_width):
        r2_train, rmse_train, r2_test, rmse_test, y_train, y_train_pred, y_test, y_test_pred, X_train_scaled, scaler, rf, X_train, y_train = evaluate_band_rf_iter(
            start_col, band_width, n_estimators=100, max_depth=None
        )

        # Store results
        results.append({
            'start_col': start_col,
            'band_width': band_width,
            'R2_train': r2_train,
            'RMSE_train': rmse_train,
            'R2_test': r2_test,
            'RMSE_test': rmse_test
        })

        # Update best model
        if r2_test > best_r2:
            best_r2 = r2_test
            best_band = (start_col, band_width)
            best_y_test = y_test
            best_y_pred = y_test_pred
            best_y_train = y_train
            best_y_train_pred = y_train_pred
            best_scaler = scaler
            best_X_train = X_train
            best_model = rf

# Convert results to DataFrame
results_df = pd.DataFrame(results)

# Display best band metrics
print(f"\nBest Band Performance:")
print(f"Start Column: {best_band[0]}, Width: {best_band[1]}")
print(f"Training R2: {results_df.loc[results_df['R2_test'].idxmax(), 'R2_train']:.4f}")
print(f"Training RMSE: {results_df.loc[results_df['R2_test'].idxmax(), 'RMSE_train']:.4f}")
print(f"Validation R2: {best_r2:.4f}")
print(f"Validation RMSE: {results_df.loc[results_df['R2_test'].idxmax(), 'RMSE_test']:.4f}")

# Visualization: R2 Across Bands
plt.figure(figsize=(12, 6))
for bw in band_widths:
    subset = results_df[results_df['band_width'] == bw]
    plt.plot(subset['start_col'], subset['R2_test'], marker='o', linestyle='-', label=f'Band Width {bw}')

plt.title('R2 Score Across Different Band Positions and Widths')
plt.xlabel('Start Column Index')
plt.ylabel('Validation R2 Score')
plt.legend()
plt.grid(True)
plt.show()

# Visualization: Actual vs Predicted for Best Band
plt.figure(figsize=(12, 6))
plt.scatter(best_y_train, best_y_train_pred, alpha=0.5, label='Training Set')
plt.scatter(best_y_test, best_y_pred, alpha=0.5, label='Validation Set')
plt.plot([min(best_y_train), max(best_y_train)], [min(best_y_train), max(best_y_train)],
         'k--', label='Perfect Prediction')
plt.title(f'Actual vs Predicted Concentrations (Best Band: {best_band[0]}-{best_band[0]+best_band[1]})')
plt.xlabel('Actual Concentration')
plt.ylabel('Predicted Concentration')
plt.legend()
plt.grid(True)
plt.show()

# Feature Importance Visualization for Best Band
band_features = features.iloc[:, best_band[0]:best_band[0]+best_band[1]]
importances = best_model.feature_importances_
indices = np.argsort(importances)[-20:]  # Top 20 features

plt.figure(figsize=(12, 6))
plt.title('Top 20 Important Features in Best Band')
plt.barh(range(len(indices)), importances[indices], align='center')
plt.yticks(range(len(indices)), [band_features.columns[i] for i in indices])
plt.xlabel('Relative Importance')
plt.tight_layout()
plt.show()

# Error Distribution Plot
errors = best_y_test - best_y_pred
plt.figure(figsize=(12, 6))
plt.hist(errors, bins=30, alpha=0.7)
plt.title('Distribution of Prediction Errors (Best Band)')
plt.xlabel('Prediction Error')
plt.ylabel('Frequency')
plt.grid(True)
plt.show()

# Binned Performance Visualization
bins = np.linspace(min(target), max(target), 10)
bin_centers = (bins[:-1] + bins[1:]) / 2
bin_indices = np.digitize(best_y_test, bins)

bin_r2 = []
bin_rmse = []
for i in range(1, len(bins)):
    mask = bin_indices == i
    if sum(mask) > 0:
        bin_r2.append(r2_score(best_y_test[mask], best_y_pred[mask]))
        bin_rmse.append(np.sqrt(mean_squared_error(best_y_test[mask], best_y_pred[mask])))
    else:
        bin_r2.append(np.nan)
        bin_rmse.append(np.nan)

plt.figure(figsize=(12, 6))
plt.plot(bin_centers, bin_r2, marker='o', label='R2 Score')
plt.plot(bin_centers, bin_rmse, marker='o', label='RMSE')
plt.title('Performance Across Concentration Bins')
plt.xlabel('Concentration Bin Center')
plt.ylabel('Metric Value')
plt.legend()
plt.grid(True)
plt.show()

!pip install seaborn
import seaborn as sns # Import seaborn as sns

# Final optimized version with comprehensive metrics and visualizations
def evaluate_band_rf_enhanced(start_col, band_width, n_estimators=200, max_depth=15):
    """Enhanced Random Forest evaluation with detailed metrics tracking"""
    band_features = features.iloc[:, start_col:start_col + band_width]

    # Train-test split with stratification
    bin_labels = pd.qcut(target, q=5, labels=False)
    X_train, X_test, y_train, y_test = train_test_split(
        band_features, target,
        test_size=0.3,
        stratify=bin_labels,
        random_state=42
    )

    # Feature scaling
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # Random Forest model with early stopping
    rf = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42,
        n_jobs=-1  # Enable parallel processing
    )
    rf.fit(X_train_scaled, y_train)

    # Predictions
    y_train_pred = rf.predict(X_train_scaled)
    y_test_pred = rf.predict(X_test_scaled)

    # Calculate metrics
    metrics = {
        'train_r2': r2_score(y_train, y_train_pred),
        'train_rmse': np.sqrt(mean_squared_error(y_train, y_train_pred)),
        'test_r2': r2_score(y_test, y_test_pred),
        'test_rmse': np.sqrt(mean_squared_error(y_test, y_test_pred)),
        'feature_importances': rf.feature_importances_,
        'model': rf,
        'scaler': scaler
    }

    return X_train, X_test, y_train, y_test, y_train_pred, y_test_pred, metrics

# Full analysis workflow
def full_band_analysis(band_widths=[50, 100, 150]):
    """Complete analysis workflow with enhanced visualizations"""
    results = []
    best_metrics = {'test_r2': -np.inf}

    for bw in band_widths:
        print(f"\n{'='*40}\nAnalyzing band width: {bw}\n{'='*40}")
        for start in range(0, features.shape[1] - bw + 1, bw//2):  # 50% overlap

            # Evaluate current band
            X_train, X_test, y_train, y_test, y_tr_pred, y_te_pred, metrics = \
                evaluate_band_rf_enhanced(start, bw)

            # Store results
            results.append({
                'band_start': start,
                'band_width': bw,
                **metrics
            })

            # Update best model
            if metrics['test_r2'] > best_metrics['test_r2']:
                best_metrics = {
                    'band_start': start,
                    'band_width': bw,
                    **metrics,
                    'X_train': X_train,
                    'X_test': X_test,
                    'y_train': y_train,
                    'y_test': y_test,
                    'y_train_pred': y_tr_pred,
                    'y_test_pred': y_te_pred
                }

    # Performance heatmap visualization
    results_df = pd.DataFrame(results)
    plt.figure(figsize=(15, 8))
    sns.heatmap(
        results_df.pivot(index='band_start', columns='band_width', values='test_r2'),
        annot=True, fmt=".2f", cmap="viridis"
    )
    plt.title("Validation R2 Scores Across Band Configurations")
    plt.xlabel("Band Width")
    plt.ylabel("Start Position")
    plt.show()

    # Best model visualizations
    if best_metrics['test_r2'] > -np.inf:
        print(f"\n{'='*40}\nBest Model Results\n{'='*40}")
        print(f"Optimal Band: Start={best_metrics['band_start']}, Width={best_metrics['band_width']}")
        print(f"Training R2: {best_metrics['train_r2']:.3f}  RMSE: {best_metrics['train_rmse']:.3f}")
        print(f"Validation R2: {best_metrics['test_r2']:.3f}  RMSE: {best_metrics['test_rmse']:.3f}")

        # Actual vs Predicted plot
        plt.figure(figsize=(12, 6))
        plt.scatter(best_metrics['y_train'], best_metrics['y_train_pred'],
                   alpha=0.5, label='Training')
        plt.scatter(best_metrics['y_test'], best_metrics['y_test_pred'],
                   alpha=0.5, label='Validation')
        plt.plot([min(target), max(target)], [min(target), max(target)],
                'k--', lw=2)
        plt.title(f"Actual vs Predicted Concentrations\n(Band: {best_metrics['band_start']}-{best_metrics['band_start']+best_metrics['band_width']})")
        plt.xlabel("Actual Concentration")
        plt.ylabel("Predicted Concentration")
        plt.legend()
        plt.grid(True)
        plt.show()

        # Feature importance visualization
        important_indices = np.argsort(best_metrics['feature_importances'])[-20:]
        plt.figure(figsize=(12, 8))
        plt.barh(
            range(len(important_indices)),
            best_metrics['feature_importances'][important_indices],
            align='center'
        )
        plt.yticks(
            range(len(important_indices)),
            [features.columns[i] for i in important_indices]
        )
        plt.title("Top 20 Important Wavelengths")
        plt.xlabel("Feature Importance Score")
        plt.tight_layout()
        plt.show()

    return best_metrics, results_df

# Execute full analysis
best_model, all_results = full_band_analysis()

# Save the best model using the captured best_pls and best_scaler
with open('best_model.pkl', 'wb') as file:
    pickle.dump((best_model, best_scaler, best_band), file)

loaded_model = pickle.load(open('best_model.pkl','rb'))
best_model, best_scaler, best_band = loaded_model

uploaded = files.upload()

# Load new dataset for inference
inference_data = pd.read_csv('Compostas (Novas) - Espetros-Inferencia.csv', delimiter=';', encoding='latin-1')

# Replace commas with periods in numeric columns
for column in inference_data.columns:
    if inference_data[column].dtype == 'object':
        inference_data[column] = pd.to_numeric(inference_data[column].str.replace(',', '.'), errors='coerce').fillna(0)

# Extract features and reduce to the best band
inference_features = inference_data.iloc[:, 4:]

# Get the best band information
band_start, band_width = best_band

# Ensure inference_band has the same columns as the training data
# Get the column names used during training
training_columns = features.columns[band_start:band_start + band_width]

# Select the corresponding columns from inference_features
# Reindex if necessary to handle missing/extra columns
inference_band = inference_features.reindex(columns=training_columns, fill_value=0)

# Preprocess inference data using the same scaler as in training
inference_scaled = best_scaler.transform(inference_band)

# Access the trained model object from the dictionary
# Assuming the model is stored under the key 'model'
trained_model = best_model['model']

# Perform prediction using the trained model
predicted_conc = trained_model.predict(inference_scaled).flatten()

# Append predictions to the dataset
inference_data = pd.concat([inference_data, pd.DataFrame({'Predicted_Conc': predicted_conc})], axis=1)

# Save the resulting dataset
inference_data.to_csv('inference_results.csv', index=False, sep=';')
print("Inference completed. Results saved to 'inference_results.csv'.")

# Plot inference data distribution
plt.figure(figsize=(10, 6))
plt.hist(predicted_conc, bins=30, alpha=0.7, label='Predicted Concentrations')
plt.title('Distribution of Predicted Concentrations (Inference)')
plt.xlabel('Concentration')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True)
plt.show()

files.download('inference_results.csv')