# -*- coding: utf-8 -*-
"""Modelo regressão com inferencia (miniNIR)_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvTIupVNqajRst4EdfbvR1BtvqE4mngw
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.cross_decomposition import PLSRegression
from sklearn.metrics import mean_squared_error, r2_score, roc_auc_score
from sklearn.preprocessing import StandardScaler
from scipy.signal import savgol_filter
import matplotlib.pyplot as plt
import joblib  # For saving the model
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from google.colab import files
import io

uploaded = files.upload()

# Load the dataset
df = pd.read_csv('2025.02.13-miniNir (solucoes simples)-Creatinina.csv', delimiter=';', encoding='latin-1')

# Data Cleaning: Convert comma decimal separator to dot and change data type
for col in df.columns[4:]:  # Columns LED1_avg to LED6_avg (Predictors)
    df[col] = df[col].str.replace(',', '.').astype(float)

df['Conc'] = df['Conc'].str.replace(',', '.').astype(float)

# Extract predictors (columns D to I) and target (column B)
X = df.iloc[:, 4:10].replace(',', '.', regex=True).astype(float)
y = df['Conc'].replace(',', '.', regex=True).astype(float)

# Preprocessing
X_smoothed = savgol_filter(X, window_length=11, polyorder=2, axis=0)
X_snv = (X_smoothed - np.mean(X_smoothed, axis=0)) / np.std(X_smoothed, axis=0)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_snv)

# Split data into training and testing sets (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.3, random_state=42)

# Define a function to evaluate regression models
def evaluate_model(model, model_name):
    model.fit(X_train, y_train)

    # Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Compute Training and Validation R^2 and RMSE
    train_r2 = r2_score(y_train, y_train_pred)
    train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
    test_r2 = r2_score(y_test, y_test_pred)
    test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

    print(f"{model_name} - Training R^2: {train_r2:.3f}, Training RMSE: {train_rmse:.3f}")
    print(f"{model_name} - Validation R^2: {test_r2:.3f}, Validation RMSE: {test_rmse:.3f}\n")

    return model, train_r2, train_rmse, test_r2, test_rmse

# Define models including PLS Regression
models = {
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "Gradient Boosting": GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, random_state=42),
    "SVR": SVR(kernel='rbf', C=1, gamma='scale'),
    "Linear Regression": LinearRegression(),
    "PLS Regression": PLSRegression(n_components=2)
}

# Evaluate models
model_results = {}
for name, model in models.items():
    best_model, train_r2, train_rmse, test_r2, test_rmse = evaluate_model(model, name)
    model_results[name] = (model, train_r2, train_rmse, test_r2, test_rmse)

# Select best model based on Validation R^2
best_model_name = max(model_results, key=lambda name: model_results[name][3])
best_model = model_results[best_model_name][0]
print(f"Best Model: {best_model_name}")

# Predict using best model for validation set
best_y_pred = best_model.predict(X_test)

# Visualization: Predicted vs Actual Concentration (Validation Only)
plt.figure(figsize=(8, 6))
plt.scatter(y_test, best_y_pred, alpha=0.7, edgecolors='k')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)  # Diagonal reference line
plt.title(f"Predicted vs Actual Concentration (Validation) - {best_model_name}")
plt.xlabel("Actual Concentration")
plt.ylabel("Predicted Concentration")
plt.grid(True)
plt.show()

# Create bins for regression confusion matrix
bins = np.linspace(y_test.min(), y_test.max(), 7)  # Adjust bin count as needed
y_test_binned = np.digitize(y_test, bins)
y_pred_binned = np.digitize(best_model.predict(X_test), bins)

# Generate and display the confusion matrix
conf_matrix = confusion_matrix(y_test_binned, y_pred_binned, labels=range(1, len(bins)))
disp = ConfusionMatrixDisplay(confusion_matrix=conf_matrix, display_labels=[f"{bins[i]:.2f}-{bins[i+1]:.2f}" for i in range(len(bins)-1)])
disp.plot(cmap="Blues", xticks_rotation=45)
plt.title("Binned Confusion Matrix")
plt.xlabel("Predicted Bin")
plt.ylabel("True Bin")
plt.tight_layout()
plt.show()

# Save the best model
joblib.dump(best_model, "best_regression_model.joblib")
print(f"Best regression model saved as 'best_regression_model.joblib'.")

# Perform PCA on the preprocessed data
pca = PCA(n_components=2)  # Reduce to 2 components for visualization
X_pca = pca.fit_transform(X_scaled)

# Add PCA components to a DataFrame for visualization
pca_df = pd.DataFrame(X_pca, columns=['PCA1', 'PCA2'])
pca_df['Target'] = y.values  # Add the target column for color coding

# Calculate explained variance percentages
explained_variance = pca.explained_variance_ratio_ * 100

# Visualization of PCA results
plt.figure(figsize=(12, 6))
plt.scatter(pca_df['PCA1'], pca_df['PCA2'], alpha=0.7, c=pca_df['Target'], cmap='viridis')
plt.colorbar(label='Target (Conc)')
plt.title('PCA Visualization of Data')
plt.xlabel(f'Principal Component 1 ({explained_variance[0]:.2f}%)')
plt.ylabel(f'Principal Component 2 ({explained_variance[1]:.2f}%)')
plt.grid(True)
plt.show()

uploaded = files.upload()

new_data = pd.read_csv('2025.02.13-miniNir (solucoes simples)-Inferencia (2).csv', delimiter=';', encoding='latin-1')
X_new = new_data.iloc[:, 4:10].replace(',', '.', regex=True).astype(float)
X_new_smooth = savgol_filter(X_new, window_length=11, polyorder=2, axis=0)
X_new_snv = (X_new_smooth - np.mean(X_new_smooth, axis=0)) / np.std(X_new_smooth, axis=0)
X_new_scaled = scaler.transform(X_new_snv)

# Predict the target variable
predictions = best_model.predict(X_new_scaled)
new_data['Predicted_Conc'] = predictions

# Save predictions to a new CSV
new_data.to_csv("predicted_concentrations.csv", index=False)
print("Predictions saved to 'predicted_concentrations.csv'.")

# Visualize Predicted vs Actual
plt.figure(figsize=(8, 6))
plt.scatter(y_test, best_model.predict(X_test), alpha=0.7, label='Predictions')
plt.plot([y.min(), y.max()], [y.min(), y.max()], 'k--', label='Ideal', color='red')
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Predicted vs Actual")
plt.legend()
plt.grid(True)
plt.show()

files.download('predicted_concentrations.csv')